  - name: app setup
    include_role:
     name: common
     tasks_from: appsetup

  - name: maven setup
    include_role:
     name: common
     tasks_from: maven

  # - name: connect to mysql using app user
  #   community.mysql.mysql_info:
  #     login_user: shipping
  #     login_password: RoboShop@1
  #     login_host: mysql.daws84s.site
  #     login_db: cities

  - name: import data
    tags:
    - import
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.daws84s.site
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: restart shipping
    tags:
    - import
    ansible.builtin.service:
      state: restarted
      name: shipping

  - name: systemd setup
    include_role:
     name: common
     tasks_from: systemd
  


  
